# Generated by Django 4.2.4 on 2023-10-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/images/default.png', upload_to='images/'),
        ),
    ]
